test:
  script:
    - echo 'init'
    - docker run -i -t hashicorp/terraform:light init
    - echo 'fmt'
    - docker run -i -t hashicorp/terraform:light fmt -check=true
    - echo 'validate'
    - docker run -i -t hashicorp/terraform:light validate