image: ubuntu
before_script:
  - echo 'before_script'
  - apt-get update -yqq
  - apt-get install -yqq curl unzip
  - export TF_WARN_OUTPUT_ERRORS=1
  - curl --silent --output terraform.zip https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
  - sha256sum terraform.zip  | grep "6b8ce67647a59b2a3f70199c304abca0ddec0e49fd060944c26f666298e23418"
  - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
  - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
  - terraform -v


test:
  script:
    - terraform init
    - terraform fmt -check=true
    - terraform validate
#    - 'ls -alh $(pwd)'
#    - echo "docker run -v $(pwd):/app/ -w /app/ hashicorp/terraform:light init"
#    - 'docker run -v $(pwd):/app/ -w /app/ hashicorp/terraform:light init'
#    - echo 'fmt'
#    - docker run -v $(pwd):/app/ -w /app/ hashicorp/terraform:light fmt -check=true
#    - echo 'validate'
#    - docker run -v $(pwd):/app/ -w /app/ hashicorp/terraform:light validate